### ISSUE TITLE
How to import?

### ISSUE THREAD

**Issue by mwindowshz** [AndrewCarterUK/pascal-voc-writer#1]
Hi found your pascal-voc-writer
did pip install

but trying to import does not work
![image](https://user-images.githubusercontent.com/17617515/41655571-edb00eaa-7495-11e8-9192-566f8e1cae23.png)

If you can please help me, and maybe add instructions you your readme file.
Thanks in advance.
M.

**Comment by AndrewCarterUK** [comment]
Hi, you want to use underscores in the import - hyphens aren't valid in python module names.

`import pascal_voc_writer`
