### ISSUE TITLE
Problem installing pascal-voc-writer

### ISSUE THREAD

**Issue by sbanerj2** [AndrewCarterUK/pascal-voc-writer#2]
I need to convert my annotation into Pascal VOC format. I am getting the following error when trying to install this:
**Collecting pascal_voc_writer
  Could not fetch URL https://pypi.python.org/simple/pascal-voc-writer/: There was a problem confirming the ssl certificate: [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590) - skipping
  Could not find a version that satisfies the requirement pascal_voc_writer (from versions: )
No matching distribution found for pascal_voc_writer**

**Comment by AndrewCarterUK** [comment]
Sounds like a problem with the Python website? Did you have this issue with other packages?

I'll reopen if you still have this issue.
